env:
  global:
    - CC_TEST_REPORTER_ID=f8db23c14ae8c24a13014972b1b0f076f133906a1693dc0d27ff39842bfe98db

language: php

php:
 - '5.6'
 - '7.2'
 - '7.3'
# - hhvm # dont work with FiltererTest::test_filterer_customizable (and I don't use hhvm)
# - nightly

# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer update --no-interaction
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

# Commands you want to run that will verify your build.
script: ./phpunit --coverage-clover=coverage.xml --testsuite=all_tests

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
 - bash <(curl -s https://codecov.io/bash)
